[package]
name = "hip_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hip_macros = {path = "./hip_macros"}
libc = "0.2.147"
libloading = "0.8.3"

[build-dependencies]
cmake = "0.1.31"