[package]
name = "hip_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
[dependencies]
cargo-emit = "0.2.1"
libloading = "0.8.3"
